name: Deploy Node.js Azure Function App

on:
  push:
    branches:
      - main  # Change this if you deploy from another branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Use the version your function app needs

      - name: Install dependencies
        run: npm install

      # Optional: Build step if your app needs it (e.g., TypeScript)
      # - name: Build project
      #   run: npm run build

      - name: Deploy to Azure Function App
        uses: Azure/functions-action@v1
        with:
          app-name: YOUR_FUNCTION_APP_NAME  # Replace with your Azure Function name
          package: '.'
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
