name: Deploy Node.js project to Azure Function App

on:
  push:
    branches: ["main"]

env:
  AZURE_FUNCTIONAPP_NAME: 'Arise12'              # Replace with your Azure Function App name
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'Arise12'            # Set to root directory
  NODE_VERSION: '20.x'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev

    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v4

    - name: Setup Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: 'Install Dependencies & Build'
      shell: bash
      working-directory: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
      run: |
        echo "Checking Node.js version..."
        node -v
        echo "Installing dependencies..."
        npm install
        echo "Running build (if applicable)..."
        npm run build --if-present
        echo "Running tests (if applicable)..."
        npm run test --if-present || echo "Tests failed or not present."

    - name: 'Deploy to Azure Function App'
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}

    - name: 'Complete'
      run: echo "Deployment completed!"
