name: Deploy Node.js project to Vercel

on:
  push:
    branches: 
      - "main"  # Trigger deployment when changes are pushed to 'main'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Set up Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: npm install

      # Step 4: Install Vercel CLI
      - name: Install Vercel CLI
        run: npm install -g vercel

      # Step 5: Optional Build Step (only if needed)
      - name: Optional Build Step
        run: npm run build --if-present

      # Step 6: Deploy to Vercel
      - name: Deploy to Vercel
        run: |
          echo "Deploying to Vercel..."
          vercel --prod --yes --token=${{ secrets.VERCEL_TOKEN }}
